exports.usermessage = {
  companyTypeInUse:
    'You can not deactivate this Company Type. Already used in companies.',
  divisionInUse:
    'Division already assigned to employees.So,you can not delete it.',
  FoodAllowancePolicyInUse:
    'Food Allowance Policy already assigned to employees.So,you can not delete it.',
  FoodAllowancePolicyInUseStatus:
    'Food Allowance Policy already assigned to employees.So,you can not deactivate it.',
  countryadd: 'Country Addded Successfully.',
  masteradminadd: 'Master admin added successfully.',
  emailvalid: 'Please enter valid email.',
  mobileNumberValid: 'Please enter valid Mobile Number.',
  passwordchange: 'Password changed successfully.',
  oldnewsame: 'Old password and new password are same.',
  oldwrong: 'Wrong old password.',
  passwordsentmail: 'Password reset code sent to your email account.',
  passwordsentMobile: 'Password reset code sent to your Mobile Number.',
  otpinvalid: 'Please enter correct otp.',
  otpVerified: 'OTP verified successfully',
  countryupdate: 'Country Updated Successfully.',
  countrydelete: 'Country Deleted Successfully',
  usernotfound: 'User not found.',
  userdeactive: 'User is deactivated.',
  companydeactive: 'Company is deactivated.',
  usersubscribeplan: 'Please subscribe any plan..',
  userdeleted: 'User is deleted.',
  companydeleted: 'Company is deleted.',
  userlogin: 'User login successfully.',
  userwronginfo: 'Please enter valid loginid and password.',
  internalservererror: 'Internal server error.',
  stateadd: 'State Addded Successfully.',
  stateupdate: 'State Updated Successfully.',
  statedelete: 'State Deleted Successfully',
  deletedrecord: 'The record is deleted.',
  protaxadd: 'Professional Tax added successfully.',
  protaxupdate: 'Professional Tax Updated Successfully.',
  protaxdelete: 'Professional Tax Deleted Successfully',
  cityadd: 'City added successfully.',
  cityupdate: 'City Updated Successfully.',
  citydelete: 'City Deleted Successfully',
  companyadd: 'Company added successfully.',
  companylist: 'Company list get successfully.',
  companyget: 'Company get successfully.',
  companyupdate: 'Company Updated Successfully.',
  companydelete: 'Comapny Deleted Successfully',
  companycontact: 'Company contact added successfully.',
  mobilealreadyexist: 'Mobile number already exist.',
  companycontactget: 'Company contact get successfully.',
  companycontactupdate: 'Company contact update successfully.',
  companycontactdelete: 'Comapny Contact Deleted Successfully',
  productadd: 'Product added successfully.',
  productupdate: 'Product Updated Successfully.',
  productdelete: 'Product Deleted Successfully',
  branchadd: 'Branch added successfully.',
  branchupdate: 'Branch Updated Successfully.',
  branchdelete: 'Branch Deleted Successfully',
  branchValidate: 'Branch Validate successfully.',
  branchReValidate: 'Branch Re-Validate successfully.',
  bankadd: 'Bank added successfully.',
  bankupdate: 'Bank Updated Successfully.',
  bankdelete: 'Bank Deleted Successfully',
  companybankadd: 'Company Bank added successfully.',
  companybankupdate: 'Company Bank Updated Successfully.',
  companybankdelete: 'Company Bank Deleted Successfully',
  companybranchexists: 'Company branch already exists',
  formadd: 'Form added successfully.',
  formupdate: 'Form Updated Successfully.',
  formdelete: 'Form Deleted Successfully',
  esicsetupadd: 'ESIC Setup added successfully.',
  esicsetupupdate: 'ESIC Setup Updated Successfully.',
  esicsetupdelete: 'ESIC Setup Deleted Successfully',
  professionalTaxSetupadd: 'Professional Tax Setup added successfully.',
  professionalTaxSetupupdate: 'Professional Tax Setup Updated Successfully.',
  professionalTaxSetupdelete: 'Professional Tax Setup Deleted Successfully',
  probationpolicyadd: 'Probation Policy Setup added successfully.',
  probationpolicyupdate: 'Probation Policy Setup Updated Successfully.',
  probationpolicydelete: 'Probation Policy Setup Deleted Successfully',
  costcenteradd: 'Cost Center Setup added successfully.',
  costcenterupdate: 'Cost Center Setup Updated Successfully.',
  costcenterdelete: 'Cost Center Setup Deleted Successfully',
  subscriptionadd: 'Subscription added successfully.',
  productupdate: 'Product Updated Successfully.',
  subscriptionupdate: 'Subscription Updated Successfully.',
  productdelete: 'Product Deleted Successfully',
  subscriptiondelete: 'Subscription Deleted Successfully',
  companyregisteradd: 'Comapny Register added successfully.',
  companyregisterget: 'Comapny Register get successfully.',
  companyregisterupdate: 'Comapny Register updated successfully.',
  companyregisterdelete: 'Comapny Register deleted successfully.',
  designationadd: 'Designation added successfully.',
  designationget: 'Designation get successfully.',
  designationupdate: 'Designation Updated Successfully.',
  designationdelete: 'Designation delete successfully.',
  departmentadd: 'Department added successfully.',
  departmentget: 'Department get successfully.',
  departmentupdate: 'Department update successfully.',
  departmentdelete: 'Department delete successfully.',
  depositCategoryadd: 'Deposit Category added successfully.',
  depositCategoryget: 'Deposit Category get successfully.',
  depositCategoryupdate: 'Deposit Category update successfully.',
  depositCategorydelete: 'Deposit Category delete successfully.',
  meetingPlaceadd: 'Meeting place added successfully.',
  meetingPlaceget: 'Meeting place get successfully.',
  meetingPlaceupdate: 'Meeting place update successfully.',
  meetingPlacedelete: 'Meeting place delete successfully.',
  gatePassadd: 'Gate Pass added successfully.',
  gatePassget: 'Gate Pass get successfully.',
  gatePassupdate: 'Gate Pass update successfully.',
  gatePassdelete: 'Gate Pass delete successfully.',
  visitorsadd: 'Visitors added successfully.',
  visitorsget: 'Visitors get successfully.',
  visitorsupdate: 'Visitors update successfully.',
  visitorsdelete: 'Visitors delete successfully.',
  visitorValidate: 'Visitors Validate successfully.',
  visitorReValidate: 'Visitors Re-Validate successfully.',
  depositadd: 'Deposit added successfully.',
  depositget: 'Deposit get successfully.',
  depositupdate: 'Deposit update successfully.',
  depositdelete: 'DeparDeposittment delete successfully.',
  branchadd: 'Branch added successfully.',
  branchupdate: 'Branch Updated Successfully.',
  branchdelete: 'Branch Deleted Successfully',
  bankadd: 'Bank added successfully.',
  bankupdate: 'Bank Updated Successfully.',
  bankdelete: 'Bank Deleted Successfully',

  professionalTaxSetupget: 'Professional Tax Setup get successfully.',
  pfSetupadd: 'PF Setup added successfully.',
  pfSetupupdate: 'PF Setup Updated Successfully.',
  pfSetupget: 'PF Setup get successfully.',
  pfSetupdelete: 'PF Setup Deleted Successfully',

  hrsalaryfieldsadd: 'HR Salary Fields added successfully.',
  hrsalaryfieldsupdate: 'HR Salary Fields Updated Successfully.',
  hrsalaryfieldsdelete: 'HR Salary Fields Deleted Successfully',
  useraddressadd: 'User address added successfully.',
  useraddressupdate: 'User address Updated Successfully.',
  useraddressdelete: 'User address Deleted Successfully',
  userexperienceadd: 'User Experience added successfully.',
  userexperienceupdate: 'User Experience Updated Successfully.',
  userexperiencedelete: 'User Experience Deleted Successfully',
  usereducationadd: 'User education added successfully.',
  usereducationupdate: 'User education Updated Successfully.',
  usereducationdelete: 'User education Deleted Successfully',
  userskillsadd: 'User skills added successfully.',
  userskillsupdate: 'User skills Updated Successfully.',
  userskillsdelete: 'User skills Deleted Successfully',
  employeereporttoadd: 'Employee Report to added successfully.',
  employeereporttoupdate: 'Employee Report to Updated Successfully.',
  employeereporttodelete: 'Employee Report to Deleted Successfully',
  employeereporttodeactive: 'The user is deactive.',
  employeedepartmentadd: 'Employee Department added successfully.',
  employeedepartmentupdate: 'Employee Department Updated Successfully.',
  employeedepartmentdelete: 'Employee Department Deleted Successfully',
  employeedepartmentactivated: 'Employee Department Activated Successfully',
  employeedesignationadd: 'Employee Designation added successfully.',
  employeedesignationupdate: 'Employee Designation Updated Successfully.',
  employeedesignationdelete: 'Employee Designation Deleted Successfully',
  employeedesignationactivated: 'Employee Designation Activated Successfully',
  shiftadd: 'Shift added successfully.',
  existingShiftPolicyName: 'Shift policy with the same name already exists.',
  shiftupdate: 'Shift Updated Successfully.',
  shiftdelete: 'Shift Deleted Successfully',
  shiftadd: 'Shift added successfully.',
  shiftupdate: 'Shift Updated Successfully.',
  shiftdelete: 'Shift Deleted Successfully',
  documentlistadd: 'Document List added successfully.',
  documentlistupdate: 'Document List Updated Successfully.',
  documentlistdelete: 'Document List Deleted Successfully',
  userdocumentadd: 'User Document added successfully.',
  userdocumentupdate: 'User Document Updated Successfully.',
  userdocumentdelete: 'User Document Deleted Successfully',
  gradestructureadd: 'Grade Structure added successfully.',
  gradestructureupdate: 'Grade Structure Updated Successfully.',
  gradestructuredelete: 'Grade Structure Deleted Successfully',
  weekoffpolicyadd: 'Weekly Off Policy added successfully.',
  weekoffpolicyupdate: 'Weekly Off Policy Updated Successfully.',
  weekoffpolicydelete: 'Weekly Off Policy Deleted Successfully',
  employeeweekoffadd: 'Employee Week Off added successfully.',
  employeeweekoffupdate: 'Employee Week Off Updated Successfully.',
  employeeweekoffdelete: 'Employee Week Off Deleted Successfully',
  employeeweekoffactivated: 'Employee Week Off Activated Successfully',
  industryadd: 'Industry added successfully.',
  industryupdate: 'Industry Updated Successfully.',
  industrydelete: 'Industry Deleted Successfully',
  visitpurposeadd: 'Visit Purpose added successfully.',
  visitpurposeupdate: 'Visit Purpose Updated Successfully.',
  visitpurposedelete: 'Visit Purpose Deleted Successfully',
  visitadd: 'Visit added successfully.',
  visitupdate: 'Visit Updated Successfully.',
  visitdelete: 'Visit Deleted Successfully',
  productadd: 'Product added successfully.',
  productupdate: 'Product Updated Successfully.',
  productdelete: 'Product Deleted Successfully',
  gradesalarystructureadd: 'Grade Salary Structure added successfully.',
  gradesalarystructureupdate: 'Grade Salary Structure Updated Successfully.',
  gradesalarystructuredelete: 'Grade Salary Structure Deleted Successfully',
  hrsalaryfieldchildeadd: 'HR Salary Field Child added successfully.',
  hrsalaryfieldchildeupdate: 'HR Salary Field Child Updated Successfully.',
  hrsalaryfieldchildedelete: 'HR Salary Field Child Deleted Successfully',
  professionalTaxSetupadd: 'Professional Tax Setup added successfully.',
  professionalTaxSetupget: 'Professional Tax Setup get successfully.',
  professionalTaxSetupupdate: 'Professional Tax Setup Updated Successfully.',
  professionalTaxSetupdelete: 'Professional Tax Setup Deleted Successfully',
  userFamilyadd: 'User family added successfully.',
  userFamilyget: 'User family get successfully.',
  userFamilyupdate: 'User family Updated Successfully.',
  userFamilydelete: 'User family Deleted Successfully',
  companydocumenttypeadd: 'Company Document type added successfully.',
  companydocumenttypeupdate: 'Company Document type Updated Successfully.',
  companydocumenttypedelete: 'Company Document type Deleted Successfully',
  companydocumentadd: 'Company Document added successfully.',
  companydocumentupdate: 'Company Document Updated Successfully.',
  companydocumentdelete: 'Company Document Deleted Successfully',
  announcementadd: 'Announcement added successfully.',
  announcementupdate: 'Announcement Updated Successfully.',
  announcementdelete: 'Announcement Deleted Successfully',
  empdigitalsignatureadd: 'Employee Digital Signature added successfully.',
  empdigitalsignatureupdate: 'Employee Digital Signature Updated Successfully.',
  empdigitalsignaturedelete: 'Employee Digital Signature Deleted Successfully',
  usertrackingadd: 'User Tracking added successfully.',
  usertrackingupdate: 'User Tracking Updated Successfully.',
  usertrackingdelete: 'User Tracking Deleted Successfully',
  usertrackingexceed: "User Tracking Exceeds company's total tracking.",
  usertrackingallow: 'User Tracking valid.',
  usertrackingdisabled: 'User Tracking disabled successfully.',
  //paheadmaster msg
  payheadadd: 'Payhead Master Added successfully.',
  payheadupdate: 'Payhead Master Updated successfully.',
  payheaddelete: 'Payhead Master Deleted successfully.',
  EmployeeBranchadd: 'Employee Branch added successfully.',
  EmployeeBranchupdate: 'Employee Branch Updated Successfully.',
  EmployeeBranchdelete: 'Employee Branch Deleted Successfully',
  EmployeeHolidayPolicyadd: 'Employee HolidayPolicy added successfully.',
  EmployeeHolidayPolicyupdate: 'Employee HolidayPolicy Updated Successfully.',
  EmployeeHolidayPolicydelete: 'Employee HolidayPolicy Deleted Successfully',
  holidaypolicyadd: 'HolidayPolicy added successfully.',
  holidaypolicyupdate: 'HolidayPolicy Updated Successfully.',
  holidaypolicydelete: 'HolidayPolicy Deleted Successfully',
  applicabledate: 'Applicable date already selected.',
  expensecategoryadd: 'Expense Category added successfully.',
  expensecategoryget: 'Expense Category get successfully.',
  expensecategoryupdate: 'Expense Category update successfully.',
  expensecategorydelete: 'Expense Category delete successfully.',
  expenseheadadd: 'Expense Head added successfully.',
  expenseheadget: 'Expense Head get successfully.',
  expenseheadupdate: 'Expense Head update successfully.',
  expenseheaddelete: 'Expense Head delete successfully.',
  expenseheadValidate: 'Expense Head Validate successfully.',
  expenseheadReValidate: 'Expense Head Re-Validate successfully.',
  officeExpenseheadAdd: 'Office Expense Head added successfully.',
  officeExpenseheadValidate: 'Office Expense Head Validate successfully.',
  officeExpenseheadReValidate: 'Office Expense Head Re-Validate successfully.',
  expensepriceruleadd: 'Expense Price Rule added successfully.',
  expensepriceruleget: 'Expense Price Rule get successfully.',
  expensepriceruleupdate: 'Expense Price Rule update successfully.',
  expensepriceruledelete: 'Expense Price Rule delete successfully.',
  assetcategoryadd: 'Asset Category added successfully.',
  assetcategoryupdate: 'Asset Category Updated Successfully.',
  assetcategorydelete: 'Asset Category Deleted Successfully',
  penaltyadd: 'Penalty added successfully.',
  penaltyupdate: 'Penalty Updated Successfully.',
  penaltydelete: 'Penalty Deleted Successfully',
  empassetadd: 'Employee asset added successfully.',
  empassetupdate: 'Employee asset Updated Successfully.',
  empassetdelete: 'Employee asset Deleted Successfully',
  empreturn: 'Employee asset Return Successfully',
  getview: 'View data found.',
  noview: 'No View data.',
  queryresults: 'Query result found.',
  emppenaltyadd: 'Employee penalty added successfully.',
  emppenaltyupdate: 'Employee penalty Updated Successfully.',
  emppenaltydelete: 'Employee penalty Deleted Successfully',
  procedurecreated: 'Procedures created successfully.',
  viewcreated: 'Views created successfully.',
  functioncreated: 'Functions created successfully.',
  visitformcustomizeadd: 'Visit Form Field added successfully.',
  visitformcustomizeupdate: 'Visit Form Field Updated Successfully.',
  visitformcustomizedelete: 'Visit Form Field Deleted Successfully',
  visitformcustomizevalueadd: 'Visit Form Field Value added successfully.',
  visitformcustomizevalueupdate: 'Visit Form Field Value Updated Successfully.',
  visitformcustomizevaluedelete: 'Visit Form Field Value Deleted Successfully',
  /**
   * Hr Leave Type Messages.
   */
  HrLeaveTypesadd: 'H.R Leave Type Added Successfully',
  HrLeaveTypesUpdate: 'H.R Leave Type Update Successfully',
  HhLeaveTypesDelete: 'H.R Leave Type Delete Successfully',
  operationadd: 'Operation added successfully.',
  operationupdate: 'Operation Updated Successfully.',
  operationdelete: 'Operation Deleted Successfully',
  //hrSalaryMaster msg
  salaryMasterAdd: 'Salary Master Added successfully.',
  salaryMasterUpdate: 'Salary Master Updated successfully.',
  salaryMasterDelete: 'Salary Master Deleted successfully.',
  //employeeJoiningDetails msg
  empJoiningAdd: 'Employee Joining Details Added successfully.',
  empJoiningUpdate: 'Employee Joining Details Updated successfully.',
  empJoiningDelete: 'Employee Joining Details Deleted successfully.',
  //AuthorizationCriteriaMaster msg
  authorizationCriteriaMasterAdd:
    'Authorization Criteria Master Added successfully.',
  authorizationCriteriaMasterUpdate:
    'Authorization Criteria Updated successfully.',
  authorizationCriteriaMasterDelete:
    'Authorization Criteria Deleted successfully.',
  visitreportadd: 'Visit Report Name added successfully.',
  visitreportupdate: 'Visit Report Name Updated Successfully.',
  visitreportdelete: 'Visit Report Name Deleted Successfully',
  dataNotFound: 'Data Not Found!',
  //HrLeaveMaster msg
  hrLeaveMasterAdd: 'Hr Leave Master Added Successfully.',
  hrLeaveMasterUpdate: 'Hr Leave Master Updated Successfully.',
  hrLeaveMasterDelete: 'Hr Leave Master Deleted Successfully.',

  hrsalaryfieldsadd: 'HR Salary Fields added successfully.',
  hrsalaryfieldsupdate: 'HR Salary Fields Updated Successfully.',
  hrsalaryfieldsdelete: 'HR Salary Fields Deleted Successfully',
  useraddressadd: 'User address added successfully.',
  useraddressupdate: 'User address Updated Successfully.',
  useraddressdelete: 'User address Deleted Successfully',
  userexperienceadd: 'User Experience added successfully.',
  userexperienceupdate: 'User Experience Updated Successfully.',
  userexperiencedelete: 'User Experience Deleted Successfully',
  usereducationadd: 'User education added successfully.',
  usereducationupdate: 'User education Updated Successfully.',
  usereducationdelete: 'User education Deleted Successfully',
  userskillsadd: 'User skills added successfully.',
  userskillsupdate: 'User skills Updated Successfully.',
  userskillsdelete: 'User skills Deleted Successfully',
  employeereporttoadd: 'Employee Report to added successfully.',
  employeereporttoupdate: 'Employee Report to Updated Successfully.',
  employeereporttodelete: 'Employee Report to Deleted Successfully',
  employeereporttodeactive: 'The user is deactive.',
  employeedepartmentadd: 'Employee Department added successfully.',
  employeedepartmentupdate: 'Employee Department Updated Successfully.',
  employeedepartmentdelete: 'Employee Department Deleted Successfully',
  employeedepartmentactivated: 'Employee Department Activated Successfully',
  employeedesignationadd: 'Employee Designation added successfully.',
  employeedesignationupdate: 'Employee Designation Updated Successfully.',
  employeedesignationdelete: 'Employee Designation Deleted Successfully',
  employeedesignationactivated: 'Employee Designation Activated Successfully',
  shiftadd: 'Shift added successfully.',
  shiftupdate: 'Shift Updated Successfully.',
  shiftdelete: 'Shift Deleted Successfully',
  shiftadd: 'Shift added successfully.',
  shiftupdate: 'Shift Updated Successfully.',
  shiftdelete: 'Shift Deleted Successfully',
  documentlistadd: 'Document List added successfully.',
  documentlistupdate: 'Document List Updated Successfully.',
  documentlistdelete: 'Document List Deleted Successfully',
  userdocumentadd: 'User Document added successfully.',
  userdocumentupdate: 'User Document Updated Successfully.',
  userdocumentdelete: 'User Document Deleted Successfully',
  gradestructureadd: 'Grade Structure added successfully.',
  gradestructureupdate: 'Grade Structure Updated Successfully.',
  gradestructuredelete: 'Grade Structure Deleted Successfully',
  weekoffpolicyadd: 'Weekly Off Policy added successfully.',
  weekoffpolicyupdate: 'Weekly Off Policy Updated Successfully.',
  weekoffpolicydelete: 'Weekly Off Policy Deleted Successfully',
  employeeweekoffadd: 'Employee Week Off added successfully.',
  employeeweekoffupdate: 'Employee Week Off Updated Successfully.',
  employeeweekoffdelete: 'Employee Week Off Deleted Successfully',
  employeeweekoffactivated: 'Employee Week Off Activated Successfully',
  customerValidate: 'Customer Validate successfully.',
  customerReValidate: 'Customer Re-Validate successfully.',
  industryadd: 'Industry added successfully.',
  industryupdate: 'Industry Updated Successfully.',
  industrydelete: 'Industry Deleted Successfully',
  visitpurposeadd: 'Visit Purpose added successfully.',
  visitpurposeupdate: 'Visit Purpose Updated Successfully.',
  visitpurposedelete: 'Visit Purpose Deleted Successfully',
  visitadd: 'Visit added successfully.',
  visitupdate: 'Visit Updated Successfully.',
  visitdelete: 'Visit Deleted Successfully',
  productadd: 'Product added successfully.',
  productupdate: 'Product Updated Successfully.',
  productdelete: 'Product Deleted Successfully',
  gradesalarystructureadd: 'Grade Salary Structure added successfully.',
  gradesalarystructureupdate: 'Grade Salary Structure Updated Successfully.',
  gradesalarystructuredelete: 'Grade Salary Structure Deleted Successfully',
  hrsalaryfieldchildeadd: 'HR Salary Field Child added successfully.',
  hrsalaryfieldchildeupdate: 'HR Salary Field Child Updated Successfully.',
  hrsalaryfieldchildedelete: 'HR Salary Field Child Deleted Successfully',
  professionalTaxSetupadd: 'Professional Tax Setup added successfully.',
  professionalTaxSetupget: 'Professional Tax Setup get successfully.',
  professionalTaxSetupupdate: 'Professional Tax Setup Updated Successfully.',
  professionalTaxSetupdelete: 'Professional Tax Setup Deleted Successfully',
  userFamilyadd: 'User family added successfully.',
  userFamilyget: 'User family get successfully.',
  userFamilyupdate: 'User family Updated Successfully.',
  userFamilydelete: 'User family Deleted Successfully',
  companydocumenttypeadd: 'Company Document type added successfully.',
  companydocumenttypeupdate: 'Company Document type Updated Successfully.',
  companydocumenttypedelete: 'Company Document type Deleted Successfully',
  companydocumentadd: 'Company Document added successfully.',
  companydocumentupdate: 'Company Document Updated Successfully.',
  companydocumentdelete: 'Company Document Deleted Successfully',
  announcementadd: 'Announcement added successfully.',
  announcementupdate: 'Announcement Updated Successfully.',
  announcementdelete: 'Announcement Deleted Successfully',
  empdigitalsignatureadd: 'Employee Digital Signature added successfully.',
  empdigitalsignatureupdate: 'Employee Digital Signature Updated Successfully.',
  empdigitalsignaturedelete: 'Employee Digital Signature Deleted Successfully',
  usertrackingadd: 'User Tracking added successfully.',
  usertrackingupdate: 'User Tracking Updated Successfully.',
  usertrackingdelete: 'User Tracking Deleted Successfully',
  usertrackingexceed: "User Tracking Exceeds company's total tracking.",
  usertrackingallow: 'User Tracking valid.',
  usertrackingdisabled: 'User Tracking disabled successfully.',
  //paheadmaster msg
  payheadadd: 'Payhead Master Added successfully.',
  payheadupdate: 'Payhead Master Updated successfully.',
  payheaddelete: 'Payhead Master Deleted successfully.',
  EmployeeBranchadd: 'Employee Branch added successfully.',
  EmployeeBranchupdate: 'Employee Branch Updated Successfully.',
  EmployeeBranchdelete: 'Employee Branch Deleted Successfully',
  EmployeeHolidayPolicyadd: 'Employee HolidayPolicy added successfully.',
  EmployeeHolidayPolicyupdate: 'Employee HolidayPolicy Updated Successfully.',
  EmployeeHolidayPolicydelete: 'Employee HolidayPolicy Deleted Successfully',
  holidaypolicyadd: 'HolidayPolicy added successfully.',
  holidaypolicyupdate: 'HolidayPolicy Updated Successfully.',
  holidaypolicydelete: 'HolidayPolicy Deleted Successfully',
  applicabledate: 'Applicable date already selected.',
  expensecategoryadd: 'Expense Category added successfully.',
  expensecategoryget: 'Expense Category get successfully.',
  expensecategoryupdate: 'Expense Category update successfully.',
  expensecategorydelete: 'Expense Category delete successfully.',
  expenseheadadd: 'Expense Head added successfully.',
  expenseheadget: 'Expense Head get successfully.',
  expenseheadupdate: 'Expense Head update successfully.',
  expenseheaddelete: 'Expense Head delete successfully.',
  expensepriceruleadd: 'Expense Price Rule added successfully.',
  expensepriceruleget: 'Expense Price Rule get successfully.',
  expensepriceruleupdate: 'Expense Price Rule update successfully.',
  expensepriceruledelete: 'Expense Price Rule delete successfully.',
  assetcategoryadd: 'Asset Category added successfully.',
  assetcategoryupdate: 'Asset Category Updated Successfully.',
  assetcategorydelete: 'Asset Category Deleted Successfully',
  penaltyadd: 'Penalty added successfully.',
  penaltyupdate: 'Penalty Updated Successfully.',
  penaltydelete: 'Penalty Deleted Successfully',
  empassetadd: 'Employee asset added successfully.',
  empassetupdate: 'Employee asset Updated Successfully.',
  empassetdelete: 'Employee asset Deleted Successfully',
  empreturn: 'Employee asset Return Successfully',
  getview: 'View data found.',
  noview: 'No View data.',
  queryresults: 'Query result found.',
  emppenaltyadd: 'Employee penalty added successfully.',
  emppenaltyupdate: 'Employee penalty Updated Successfully.',
  emppenaltydelete: 'Employee penalty Deleted Successfully',
  procedurecreated: 'Procedures created successfully.',
  viewcreated: 'Views created successfully.',
  functioncreated: 'Functions created successfully.',
  visitformcustomizeadd: 'Visit Form Field added successfully.',
  visitformcustomizeupdate: 'Visit Form Field Updated Successfully.',
  visitformcustomizedelete: 'Visit Form Field Deleted Successfully',
  visitformcustomizevalueadd: 'Visit Form Field Value added successfully.',
  visitformcustomizevalueupdate: 'Visit Form Field Value Updated Successfully.',
  visitformcustomizevaluedelete: 'Visit Form Field Value Deleted Successfully',
  /**
   * Hr Leave Type Messages.
   */
  HrLeaveTypesadd: 'H.R Leave Type Added Successfully',
  HrLeaveTypesUpdate: 'H.R Leave Type Update Successfully',
  HhLeaveTypesDelete: 'H.R Leave Type Delete Successfully',
  operationadd: 'Operation added successfully.',
  operationupdate: 'Operation Updated Successfully.',
  operationdelete: 'Operation Deleted Successfully',
  //hrSalaryMaster msg
  salaryMasterAdd: 'Salary Master Added successfully.',
  salaryMasterUpdate: 'Salary Master Updated successfully.',
  salaryMasterDelete: 'Salary Master Deleted successfully.',

  //AuthorizationCriteriaMaster msg
  authorizationCriteriaMasterAdd:
    'Authorization Criteria Master Added successfully.',
  authorizationCriteriaMasterUpdate:
    'Authorization Criteria Updated successfully.',
  authorizationCriteriaMasterDelete:
    'Authorization Criteria Deleted successfully.',
  visitreportadd: 'Visit Report Name added successfully.',
  visitreportupdate: 'Visit Report Name Updated Successfully.',
  visitreportdelete: 'Visit Report Name Deleted Successfully',

  //hr leave monthly trans msgs
  DeleteHrLeavesMonthlyTrans: 'Hr Leave Monthly Trans deleted successfully,',
  AddHrLeavesMonthlyTrans: 'Hr Leave Monthly Trans added successfully.',
  UpdateHrLeaveMonthlyTrans: 'Hr Leave Monthly Trans Update successfully.',
  hrleavemonthlytransupdate: 'Data updated successfully.',
  hrleavemonthtransnotfound: 'Hr Leave Monthly Trans Not Found!!',
  hrleavemonthlytransdatanotfound: 'Data not updated, data not found',

  visitadd: 'Visit added successfully.',
  visitupdate: 'Visit Updated Successfully.',
  visitdelete: 'Visit Deleted Successfully',

  visitreportcustomizeadd: 'Visit Report Field added successfully.',
  visitreportcustomizeupdate: 'Visit Report Field Updated Successfully.',
  visitreportcustomizedelete: 'Visit Report Field Deleted Successfully',
  visitreportcustomizevalueadd: 'Visit Report Field Value added successfully.',
  visitreportcustomizevalueupdate:
    'Visit Report Field Value Updated Successfully.',
  visitreportcustomizevaluedelete:
    'Visit Report Field Value Deleted Successfully',
  getprofile: 'Profile get successfully.',
  profileupdate: 'Profile updated successfully.',
  userrightget: 'User Rights get successfully.',
  userrightnotfound: 'User Rights not found.',

  //leave
  userleaveupdate: 'Leave update succesfully.',
  userleavedelete: 'Leave delete succefully.',
  userleaveadd: 'Leave added succesfully.',

  //userleaveBal
  leavebaladd: 'User Balance Added Successfully.',
  leavebalupdate: 'User Balance Update Successfully.',

  mailconfigurationadd: 'Mail configuration added successfully.',
  mailconfigurationupdate: 'Mail configuration Updated Successfully.',
  mailconfigurationdelete: 'Mail configuration Deleted Successfully',
  mailconfigurationwrong: 'You entred wrong details.',

  preboardingadd: 'Preboarding added successfully.',
  preboardingupdate: 'Preboarding Updated Successfully.',
  preboardingdelete: 'Preboarding Deleted Successfully',
  preboardingwrong: 'You entred wrong details.',

  preboardingformcustomizevalueadd:
    'Preboarding Form Field Value added successfully.',
  preboardingformcustomizevalueupdate:
    'Preboarding Form Field Value Updated Successfully.',
  preboardingformcustomizevaluedelete:
    'Preboarding Form Field Value Deleted Successfully',

  preboardingformcustomizeadd: 'Preboarding Form Field added successfully.',
  preboardingformcustomizeupdate:
    'Preboarding Form Field Updated Successfully.',
  preboardingformcustomizedelete: 'Preboarding Form Field Deleted Successfully',

  callfollowupadd: 'Call Followup added successfully.',
  callfollowupget: 'Call Followup get successfully.',
  callfollowupupdate: 'Call Followup update successfully.',
  callfollowupdelete: 'Call Followup delete successfully.',
  hrleavemonthtransnotfound: 'Hr Leave Monthly Trans Not Found!!',
  hrleavemonthlytransdatanotfound: 'Data not updated, data not found.',

  //loan master
  LoanMasteradd: 'Loan master data added successfully.',
  LoanMasternotFound: 'Loan master data not found.',
  LoanMasterdatadeleted: 'Loan master data deleted successfully.',
  LoanMasterupdate: 'Data updated successfully.',
  loantransactionnotfound: 'Loan transaction not found.',
  loanAmountNotMatch:
    'The loan principal amount does not match the specified loan amount.',

  //form 16
  form16dataandchildsave: 'Form16 data and child data added successfully.',
  form16datasave: 'Form16 data saved successfully.',
  form16datadeleted: 'Form16 data and child data deleted successfully.',
  form16childdeleted: 'Form 16 child data deleted successfully.',
  form16dataupdate: 'Form 16 data updated successfully.',
  form16childdataupdate: 'Form 16 data and child data updated successfully.',
  form16datanotfound: 'Form 16 data not found.',

  //investment details
  AddInvestmentDetails: 'Investment details added sucessfully.',
  Investmentdetailsdeleted: 'Investment details deleted successfully.',
  Investmentdetailsdatanotfound: 'Investment details not found.',
  Investmentdetailsupdated: 'Investment details updated successfully.',
  investmentdetailsnotfound: 'Investment details data not found.',

  //tds slab master
  tdsslabmasterdata: 'Tds Slab Master data added successfully.',
  TdsSlabMasterdeleted: 'Tds slab master data deleted successfully.',
  TdsSlabMasterupdated: 'Tds slab master data updated successfully',
  TDSslabnotfound: 'Tds slab master data not found.',

  //tax challan master
  taxchallanmasterdata: 'Tax challan master data added successfully',
  TaxChallanMasterdeleted: 'Tax challan master data deleted successfully.',
  TaxChallanMasterupdated: 'Tax challan master data updated successfully.',
  taxchallanmasternotfound: 'Tax challan master data not found.',

  //quarter tax challan
  quartertaxchallansave: 'Quarter tax challan data added successsfully.',
  quartertaxchallandelete: 'Quarter tax challan data deleted successfully.',
  quartertaxchallanupdate: 'Quarter tax challan data updated successfully.',
  quartertaxchallannotfound: 'Quarter tax challan data not found.',

  //attendance logs
  attendancelogsadd: 'Attendance logs data added successfully',
  attendancelogsupdate: 'Attendance logs data updated successfully',
  attendancelogsnotfound: 'Attendance logs data not found',
  attendancelogdatadeleted: 'Attendance log data deleted successfully',

  Trackingdelete: 'User Tracking Deleted sucessfully',
  Trackingadd: 'Tracking added sucessfully',
  Trackingupdate: 'Tracking updated sucessfully',
  errmessage: 'Operation is not sucessfull',

  toursMasteradd: 'Tour added successfully',
  toursMasterupdate: 'Tour updated successfully',
  toursMasterdelete: 'Tour Deleted Successfully',

  versionupdate: 'Version Updated Successfully.',
  versionnotmatch: 'Please update app version.',
  DashboardGet: 'Dashboard get Successfully.',

  preboardingrequestadd: 'Preboarding request added successfully.',
  preboardingrequestupdate: 'Preboarding request Updated Successfully.',
  preboardingrequestdelete: 'Preboarding request Deleted Successfully',

  //AttendanceTransaction Meassages
  attendancetransactionadd: 'Attendance Transaction added Succesfully',
  attendanceTransactionupdate: 'Attendance Transaction Updated Succesfully',
  attendanceTransactiondelete: 'Attendance Transaction Deleted Succesfully',
  attendanceTransactionStatus:
    'Attendance Transaction Status Updated Succesfully',

  //Advanvce Payment
  advancepaymentadd: 'Advance Payment Details Added Succesfully',
  advancepaymentupdate: 'Advance Payment Details Updated Succesfully',
  advancepaymentdelete: 'Advance Payment Details Deleted Succesfully',
  advancepaymentStatus: 'Advance Payment Details Status Updated Succesfully',

  //Advanvce Payment
  otherpaymentadd: 'Other Payment Details Added Succesfully',
  otherpaymentupdate: 'Other Payment Details Updated Succesfully',
  otherpaymentdelete: 'Other Payment Details Deleted Succesfully',
  otherpaymentStatus: 'Other Payment Details Status Updated Succesfully',

  employeeshiftadd: 'Employee Shift added successfully.',
  employeeshiftdate: 'Date already added.',
  employeeshiftupdate: 'Employee Shift updated successfully.',
  employeeshiftdelete: 'Employee Shift Deleted Successfully',

  attendancepolicyadd: 'Attendance Policy added successfully.',
  attendancepolicyupdate: 'Attendance Policy Updated Successfully.',
  attendancepolicydelete: 'Attendance Policy Deleted Successfully',
  existingPolicyName: 'Attendance policy with the same name already exists.',

  salarypolicyadd: 'Salary added successfully.',
  salarypolicyupdate: 'Salary Updated Successfully.',
  salarypolicydelete: 'Salary Deleted Successfully',

  employeeattendancepolicyadd: 'Employee attendance policy added successfully.',
  employeeattendancepolicydate: 'Date already added.',
  employeeattendancepolicyupdate: 'Employee attendance policy successfully.',
  employeeattendancepolicydelete: 'Employee attendance policy Successfully',

  employeesalarypolicyadd: 'Employee Salary policy added successfully.',
  employeesalarypolicydate: 'Date already added.',
  employeesalarypolicyupdate: 'Employee Salary policy successfully.',
  employeesalarypolicydelete: 'Employee Salary policy Successfully',
  //company letter format
  CompanyLetterAdd: 'Company Letter Format added successfully',
  companyLetterFormatUpdated: 'Company letter format updated successfully',
  letterFormatNotFound: 'Letter Format Not found',
  companyLetterFormatDeleted: 'Letter Format Deleted successfully',
  //overTimePolicy
  overTimePolicyAdd: 'OvertimePolicy added successfully',
  overTimePolicyUpdate: 'OvertimePolicy Updated successfully',
  overTimePolicyDelete: 'OvertimePolicy deleted successfully',
  overTimePolicyStatus: 'OvertimePolicy status updated successfully',

  //userOverTimePolicyAssign
  userOverTimePolicyAssignAdd: 'userOverTimePolicyAssign added successfully',
  userOverTimePolicyAssignUpdate:
    'userOverTimePolicyAssign Updated successfully',
  userOverTimePolicyAssignDelete:
    'userOverTimePolicyAssign deleted successfully',
  userOverTimePolicyAssignStatus:
    'userOverTimePolicyAssign status updated successfully',

  //overTime
  overTimeAdd: 'Overtime added successfully',
  overTimeUpdate: 'Overtime Updated successfully',
  overTimeDelete: 'Overtime deleted successfully',
  // overTimeStatus: 'Overtime status updated successfully'

  employeepolicyadd: 'Employee policy added successfully.',
  authaccept: 'Authorization Request accept successfully.',
  authreject: 'Authorization Request reject successfully.',

  punchin: 'PunchIn successfully.',
  punchout: 'PunchOut successfully.',
  shiftadds: 'Please add shift.',
  punchoutcond: 'Please add new punchin / punchout old punchin.',
  userexceed: "User Exceeds company's total user.",
  userallow: 'User valid.',
  attendancedata: 'Attendance get successfully.',

  authorizationMasteradd: 'Authorization added successfully.',
  authorizationMasterupdate: 'Authorization Updated Successfully.',
  authorizationMasterdelete: 'Authorization Deleted Successfully',

  expenseadd: 'Expense added successfully.',
  expenseupdate: 'Expense Updated Successfully.',
  expensedelete: 'Expense Deleted Successfully',

  trackingget: 'Tracking data get successfully.',
  contactadmin: 'Please contact to admin.',

  overtimeMasteradd: 'Overtime added successfully',
  overtimeMasterupdate: 'Overtime updated successfully',
  overtimeMasterdelete: 'Overtime Deleted Successfully',
  radiusnotmatch: 'You are not in attendance area.',
  assignshift: 'Please contact to admin for assign shift.',
  uniqueidremove: 'Unique Id removed successfully.',
  useralldata: 'User all date get successfully.',
  visitget: 'Visit Get Successfully',

  overtimedataget: 'Overtime data get successfully.',
  overtimedataupdate: 'Overtime data updated successfully.',
  overtimedatadelete: 'Overtime data deleted successfully.',

  salarydelte: 'Salary data deleted successfully.',
  attendancedelte: 'Attendence data deleted successfully.',

  ndacategory: 'NDA Category Data Added Successfully',
  ndaupdate: 'NDA Category Data Updated Successfully',
  ndadelete: 'NDA Category Data Deleted Successfully',
  ndaCategoryValidate: 'NDA Category Validate successfully.',
  ndaCategoryReValidate: 'NDA Category Re-Validate successfully.',

  employeeNda: 'Employee NDA Data Added Successfully',
  employeeupdate: 'Employee NDA Data Updated Successfully',
  employeedelete: 'Employee NDA Data Deleted Successfully',

  assetmasteradd: 'Asset Master Added Successfully.',
  assetmasterupdate: 'Asset Master Updated Successfully.',
  assetmasterdelete: 'Asset Master Deleted Successfully.',

  incrementadd: 'Increment added successfully.',

  employeementadd: 'Employeement added successfully.',
  employeementupdate: 'Employeement updated successfully.',
  employeementdelete: 'Employeement deleted successfully.',

  employeeEmployeementmentadd: 'employeeEmployeementment added successfully.',
  employeeEmployeementUpdate: 'employeeEmployeementment updated successfully.',
  employeeEmployeementDelete: 'employeeEmployeementment deleted successfully.',

  erpAccountMasteradd: 'Erp Account Master added successfully.',
  erpAccountMasterupdate: 'Erp Account Master updated successfully.',
  erpAccountMasterdelete: 'Erp Account Master deleted successfully.',

  userLogsadd: 'User Logs added successfully.',
  userLogsupdate: 'User Logs updated successfully.',
  userLogsdelete: 'User Logs deleted successfully.',
  letterHeadAdd: 'LetterHead Added Successfully.',
  letterHeadUpdate: 'LetterHead Updated Successfully.',
  letterHeadDelete: 'LetterHead Deleted Successfully.',

  empletterHeadAdd: 'Letter Added Successfully.',
  empletterHeadUpdate: 'Letter Updated Successfully.',
  empletterHeadDelete: 'Letter Deleted Successfully.',
  departmentareadyexist: 'Department already exist.',
  designatiomareadyexist: 'Designation already exist.',
  leavetypealreadyexist: 'Leave Type already exist.',

  unvarifyAttendanceCalculation:
    'Attendance Calculation Unverified Successfully ',
  varifyAttendanceCalculation: 'Attendance Calculation verified Successfully ',
  notleavebalance: `You don't have sufficient leave balance.`,

  //incentivetype
  incentivetypeadd: 'Incentive type data added successfully',
  incentivetypedelete: 'Incentive type data delete successfully',
  incentivetypeupdate: 'Incentive type data Update successfully',

  //employeeincentive
  employeeincentiveadd: 'Employee incentive data added successfully',
  employeeincentivedelete: 'Employee incentive data delete successfully',
  employeeincentiveupdate: 'Employee incentive data Update successfully',

  leavecancel: 'Leave Cancelled Successfully',
  addEmpAccident: 'Employee Accident Details Added successfully',
  editEmpAccident: 'Employee Accident Details Updated successfully',
  deleteEmpAccident: 'Employee Accident Details Deleted successfully',
  reqadvancepaymentadd: 'Advance Payment Request Details Added Succesfully',

  // Skill Sets
  skillsetsadd: 'Skillset Details Added Succesfully',
  skillsetsupdate: 'Skillset Details Updated Succesfully',
  skillsetsdelete: 'Skillset Details Deleted Succesfully',
  skillsetsStatus: 'Skillset Details Status Updated Succesfully',
  skillsetsrecord: 'The record not found.',

  Modulenameadd: 'Module added successfully.',
  Modulenameupdate: 'Module Updated Successfully.',
  Modulenamedelete: 'Module Deleted Successfully',

  ModuleDetailsadd: 'Module Details added successfully.',
  ModuleDetailsupdate: 'Module Details Updated Successfully.',
  ModuleDetailsdelete: 'Module Details Deleted Successfully',

  addLeadMaster: 'Lead Master Added successfully.',
  completeRegistration: 'Registration Completed successful!!!',

  addLeadMaster: 'Lead Master Added successfully.',
  completeRegistration: 'Registration Completed successful!!!',

  //leadMaster
  leadMasteradd: 'Lead added successfully.',

  //EmployeeJoiningRequest
  addemployeeJoiningRequest: 'Employee Joining Request added successfully.',
  getemployeeJoiningRequestByID: 'Employee Joining Request GET successfully',
  editemployeeJoiningRequest: 'Employee Joining Request Updated Successfully.',
  editStatusemployeeJoiningRequest:
    'Employee Joining Request Status Updated Successfully.',

  addMessage: (fieldName) => `${fieldName} added successfully!`,
  alreadyExists: (fieldName) => `${fieldName} already exists!`,
  fetchMessage: (fieldName) => `${fieldName} fetched successfully!`,
  updateMessage: (fieldName) => `${fieldName} updated successfully!`,
  deleteMessage: (fieldName) => `${fieldName} deleted successfully!`,
  activeMessage: (fieldName) => `${fieldName} activated successfully`,
  deactiveMessage: (fieldName) => `${fieldName} deactivated successfully`,
  renewMessage: (fieldName) => `${fieldName} Re-Newed successfully!`,
  notFoundMessage: (fieldName) => `${fieldName} not found!`,
  invalidField: (fieldName) => `Please enter a valid ${fieldName}!`,
  sessionExpired: 'Your session has been expired. Please login again!',
  canNotDelete: (fieldName) =>
    `Cannot delete record. Related ${fieldName} exist!`,
  alreadyAssign: (fieldName, type) =>
    `This ${fieldName} cannot be ${type}. Employees have already been assigned.`,
  acceptMesaage: (fieldName) => `${fieldName} approved successfully.`,
  rejectMessage: (fieldName) => `${fieldName} rejected successfully.`,
  cancelMessage: (fieldName) => `${fieldName} Cancelled Succefully!`,
  validateMessage: (fieldName) => `${fieldName} Validate successfully.`,
  reValidateMessage: (fieldName) => `${fieldName} Re-Validate successfully.`,
  completeMessage: (fieldName) => `${fieldName} Completed successfully.`,
  assignMessage: (fieldName) => `${fieldName} assigned successfully!`,
  requiredMessage: (fieldName) => `${fieldName} is required field!`,
  removeMessage: (fieldName) => `${fieldName} removed successfully.`,
  reapplyMessage: (fieldName) => `${fieldName} Reapplied successfully.`,
  expenseDatePicker: (fieldName) =>
    `You cannot apply expense after ${fieldName} days.`,
  approveMessage: (fieldName) => `${fieldName} approved successfully`,
  rejectMessage: (fieldName) => `${fieldName} rejected successfully`,
  validDateRange: () => `Fromdate should be less then Or equal to todate `,
  alreadyAssignToProject: (fieldName, type) =>
    `This ${fieldName} cannot be ${type}. Project have already been assigned.`,
  passValidValidParameter: (fieldName) => `Please Pass Valid${fieldName} `,
  validDateFormat: (fieldName) =>
    `Please enter ${fieldName} date in YYYY-MM-DD format!`,
  validMonthFormat: (fieldName) =>
    `Please enter ${fieldName} Month in YYYYMM format!`,
  notFoundBranchJob: (fieldName, name) =>
    `${fieldName} with name ${name} not found!`,

  returnMessage: (fieldName) => `${fieldName} return successfully`,

  departmentValidate: 'Department Validate successfully.',
  departmentadd: 'Department added successfully.',
  designationValidate: 'Designation Validate successfully.',
  designationadd: 'Designation added successfully.',
  divisionValidate: 'Division Validate successfully.',
  divisionadd: 'Division added successfully.',
  workingAreaValidate: 'Working Area Validate successfully.',
  workingAreaadd: 'Working Area added successfully.',
  expenseCategoryValidate: 'Expense Category Validate successfully.',
  expenseCategoryadd: 'Expense Category added successfully.',
  depositCategoryValidate: 'Deposit Category Validate successfully.',
  depositCategoryadd: 'Deposit Category added successfully.',
  assetCategoryValidate: 'Asset Category Validate successfully.',
  assetCategoryadd: 'Asset Category added successfully.',
  meetingPlaceValidate: 'Meeting Place Validate successfully.',
  meetingPlaceadd: 'Meeting Place added successfully.',
  taskStagesValidate: 'Task Stages Validate successfully.',
  taskStagesadd: 'Task Stages added successfully.',
  visitPurposeValidate: 'Visit Purpose Validate successfully.',
  visitPurposeadd: 'Visit Purpose added successfully.',
  workingLocationadd: 'Working Location added successfully.',
  workingLocationValidate: 'Working Location Validate successfully.',
  workingLocationReValidate: 'Working Location Re-Validate successfully.',
  shortLeaveAddSuccess: 'Short Leave added successfully.',
  shortLeaveEditSuccess: 'Short Leave updated successfully.',
  shortLeaveDeleteSuccess: 'Short Leave deleted successfully.',
  shortLeaveExist: 'Short Leave with the same name already exists.',
  shortLeaveStatusChange: 'Short Leave Status has been changed.',
  shortLeavePolicyNotFound: 'Short Leave Policy not found!',
  taskUpdateSuccess: 'Task Updated Successfully',
  taskUpdateSuccessCron:
    'Task Updated Successfully but cron will be run on production only.',
  trackingOutageCategoryAdd: 'Tracking outage category added successfully.',
  trackingOutageCategoryExist: 'Tracking outage category already exists.',
  trackingOutageCategoryUpdate:
    'Tracking outage category updated successfully.',
  trackingOutageCategoryDelete:
    'Tracking outage category deleted successfully.',
  trackingOutageCategoryStatusUpdate:
    'Tracking outage category status updated successfully.',
  trackingCategoryDetailAdd: 'Tracking category detail added successfully.',
  trackingCategoryDetailExist: 'Tracking category detail already exists.',
  trackingCategoryDetailUpdate:
    'Tracking category detail updated successfully.',
  trackingCategoryDetailDelete:
    'Tracking category detail deleted successfully.',
  trackingCategoryDetailStatusUpdate:
    'Tracking outage category detail status updated successfully.',
  ValidParameters: 'Pass valid Perameter!',
  customeradd: 'Customer added successfully.',
  customerupdate: 'Customer Updated Successfully.',
  customerdelete: 'Customer Deleted Successfully',
};

exports.errorMessage = {
  UNAUTHORIZED_ACCESS: 'You do not have access to perform this action!',
  INTERNAL_SERVER_ERROR: 'Internal Server Error!',
  INVALID_FILTER_FIELDS: 'Please apply valid filter to fetch the data!',
  INVALID_REQUEST: 'Invalid Request!',
  SENTIMENT_ALREADY_PUNCHED: "You've already punched sentiments for today!",
  GOAL_FINANCIAL_YEAR:
    'Goal start date and date must be in between financial year!',
  GOAL_CALENDAR_YEAR:
    'Goal start date and date must be in between calendar year!',
  KRA_WEIGHTAGE_EXCEEDS: (remainingWeightage) =>
    `Weightage limit exceeded. The goal already contains KRAs with an accumulative weightage of ${
      100 - remainingWeightage
    }%. You can only add KRAs with a combined weightage of up to ${remainingWeightage}%.`,
  KPI_WEIGHTAGE_EXCEEDS: (remainingWeightage) =>
    `Weightage limit exceeded. The KRA already contains KPIs with an accumulative weightage of ${
      100 - remainingWeightage
    }%. You can only add KPIs with a combined weightage of up to ${remainingWeightage}%.`,
  EMPLOYEE_GOAL_REPORT_NOT_READY:
    'Report for this employee can not be prepared!',
};
